CREATE DATABASE GoGame
GO
USE GoGame
GO

CREATE TABLE MsStaff (
StaffID VARCHAR(5) PRIMARY KEY CHECK (StaffID LIKE 'ST[0-9][0-9][0-9]'),
StaffName VARCHAR(100) NOT NULL,
StaffGender VARCHAR(6) NOT NULL CHECK (StaffGender LIKE 'Male' OR StaffGender LIKE 'Female'),
StaffDOB DATE NOT NULL,
StaffSalary BIGINT NOT NULL,
StaffPhone BIGINT NOT NULL,
StaffAddress VARCHAR(300) NOT NULL
)

CREATE TABLE MsGameType ( 
GameTypeID VARCHAR(5) PRIMARY KEY CHECK (GameTypeID LIKE 'GT[0-9][0-9][0-9]'),
GameTypeName VARCHAR(100) NOT NULL
) 

CREATE TABLE MsGamePrice(
GamePriceID VARCHAR (5) PRIMARY KEY CHECK (GamePriceID LIKE 'PR[0-9][0-9][0-9]'),
GamePurchase BIGINT NOT NULL,
GameSales BIGINT NOT NULL,
)

CREATE TABLE MsGame(
GameID VARCHAR (5) PRIMARY KEY CHECK (GameID LIKE 'GA[0-9][0-9][0-9]'),
GameTypeID VARCHAR (5) FOREIGN KEY REFERENCES MsGameType(GameTypeID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
GameName VARCHAR (50) NOT NULL CHECK (LEN(GameName)>=5),
GamePriceID VARCHAR (5) FOREIGN KEY REFERENCES MsGamePrice(GamePriceID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
GameReleaseDate DATE CHECK (GameReleaseDate <= GETDATE()) NOT NULL,
GameStock INT NOT NULL
)

CREATE TABLE MsCustomer (
CustomerID VARCHAR(5) PRIMARY KEY CHECK (CustomerID LIKE 'CU[0-9][0-9][0-9]'),
CustomerName VARCHAR (100) NOT NULL,
CustomerGender VARCHAR(6) CHECK (CustomerGender LIKE 'Male' OR CustomerGender LIKE 'Female') NOT NULL,
CustomerDOB DATE NOT NULL,
CustomerPhone BIGINT NOT NULL
)

CREATE TABLE MsSupplier(
SupplierID VARCHAR(5) PRIMARY KEY CHECK (SupplierID LIKE 'SU[0-9][0-9][0-9]'),
SupplierName VARCHAR (100) NOT NULL,
SupplierAddress VARCHAR(300)  NOT NULL,
SupplierPhone BIGINT NOT NULL
)

CREATE TABLE SalesTr(
SalesID VARCHAR (5) PRIMARY KEY CHECK (SalesID LIKE 'SA[0-9][0-9][0-9]'),
SalesDate DATE NOT NULL,
StaffID VARCHAR (5) FOREIGN KEY REFERENCES MsStaff (StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
CustomerID VARCHAR (5) FOREIGN KEY REFERENCES MsCustomer (CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
)

CREATE TABLE SalesTrDetail(
SalesID VARCHAR (5) FOREIGN KEY REFERENCES SalesTr (SalesID)  ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
GameID VARCHAR (5) FOREIGN KEY REFERENCES MsGame (GameID)  ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
SalesQuantity INT NOT NULL
)

CREATE TABLE PurchaseTr(
PurchaseID VARCHAR (5) PRIMARY KEY CHECK (PurchaseID LIKE 'PU[0-9][0-9][0-9]'), 
PurchaseDate DATE NOT NULL,
StaffID VARCHAR (5) FOREIGN KEY REFERENCES MsStaff (StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
SupplierID VARCHAR (5) FOREIGN KEY REFERENCES MsSupplier(SupplierID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
)

CREATE TABLE PurchaseTrDetail(
PurchaseID VARCHAR (5) FOREIGN KEY REFERENCES PurchaseTr(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
GameID VARCHAR(5) FOREIGN KEY REFERENCES MsGame(GameID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
PurchaseQuantity INT NOT NULL
)
